### ISSUE TITLE
Whitelist wildcard domain

### ISSUE THREAD

**Issue by dogancelik** [henrypp/hostsmgr#8]
I'd like to whitelist all subdomains of a particular domain.

For example Amazon has subdomains like these:

```
v-eu-preprod.amazon-adsystem.com
vaes-preprod.dub.amazon-adsystem.com
da-v-eu.amazon-adsystem.com
assoc-msdk-metrics-us.amazon-adsystem.com
vaes.iad.amazon-adsystem.com
aax-us-east-rtb-adx.amazon-adsystem.com
```

I want to whitelist all of them with `*.amazon-adsystem.com`

If I want to whitelist `amazon-adsystem.com` (not subdomain), I can use: `amazon-adsystem.com` (no wildcard)

**Comment by ghost** [comment]
@dogancelik: Wildcard doesn’t work in Hosts file i.e., you cannot put *.example.com to block all of the subdomains of example.com You have to enter the subdomains one by one to block them. 

This is not a restriction of hostsmgr. The problem is Hosts file.

https://community.spiceworks.com/topic/2180586-host-file-use-wildcard-to-block-domain-extensions
https://superuser.com/questions/135595/using-wildcards-in-names-in-windows-hosts-file

**Comment by dogancelik** [comment]
I know Hosts file can't do that, I'm asking hostsmgr to filter any specified domain and its subdomains if there's a wildcard in the domain. I explained the issue in my first message. Since there are hundreds of Amazon domains and more added every day, I can not keep track of them all, that's why I want to *exclude* any of them with the wildcard while hostsmgr is fetching domains.
